#!/usr/bin/env python3
"""
Перевод арабского файла сообщений
"""

import re
import os

# Арабские переводы
AR_TRANSLATIONS = {
    'Downloading': 'جاري التحميل',
    'Processing': 'جاري المعالجة', 
    'Complete': 'مكتمل',
    'Error': 'خطأ',
    'Failed': 'فشل',
    'Success': 'نجح',
    'Warning': 'تحذير',
    'Settings': 'الإعدادات',
    'Help': 'المساعدة',
    'Close': 'إغلاق',
    'Back': 'رجوع',
    'Next': 'التالي',
    'Cancel': 'إلغاء',
    'Confirm': 'تأكيد',
    'Save': 'حفظ',
    'Delete': 'حذف',
    'Edit': 'تعديل',
    'Add': 'إضافة',
    'Remove': 'إزالة',
    'Update': 'تحديث',
    'Refresh': 'تحديث',
    'Search': 'بحث',
    'Filter': 'تصفية',
    'Sort': 'ترتيب',
    'Download': 'تحميل',
    'Upload': 'رفع',
    'Send': 'إرسال',
    'Receive': 'استقبال',
    'Start': 'بدء',
    'Stop': 'إيقاف',
    'Pause': 'إيقاف مؤقت',
    'Resume': 'متابعة',
    'Retry': 'إعادة المحاولة',
    'Continue': 'متابعة',
    'Finish': 'إنهاء',
    'Done': 'تم',
    'Ready': 'جاهز',
    'Loading': 'جاري التحميل',
    'Waiting': 'انتظار',
    'Please wait': 'يرجى الانتظار',
    'Please try again': 'يرجى المحاولة مرة أخرى',
    'Try again': 'حاول مرة أخرى',
    'Invalid': 'غير صالح',
    'Valid': 'صالح',
    'Available': 'متاح',
    'Unavailable': 'غير متاح',
    'Enabled': 'مفعل',
    'Disabled': 'معطل',
    'On': 'تشغيل',
    'Off': 'إيقاف',
    'Yes': 'نعم',
    'No': 'لا',
    'OK': 'موافق',
    'Apply': 'تطبيق',
    'Reset': 'إعادة تعيين',
    'Default': 'افتراضي',
    'Custom': 'مخصص',
    'Auto': 'تلقائي',
    'Manual': 'يدوي',
    'Automatic': 'تلقائي',
    'Quality': 'جودة',
    'Format': 'تنسيق',
    'Size': 'حجم',
    'Duration': 'مدة',
    'Title': 'عنوان',
    'Description': 'وصف',
    'Name': 'اسم',
    'Type': 'نوع',
    'Status': 'حالة',
    'Progress': 'تقدم',
    'Speed': 'سرعة',
    'Time': 'وقت',
    'Date': 'تاريخ',
    'File': 'ملف',
    'Folder': 'مجلد',
    'Directory': 'دليل',
    'Path': 'مسار',
    'URL': 'رابط',
    'Link': 'رابط',
    'Video': 'فيديو',
    'Audio': 'صوت',
    'Image': 'صورة',
    'Photo': 'صورة',
    'Picture': 'صورة',
    'Media': 'وسائط',
    'Content': 'محتوى',
    'Data': 'بيانات',
    'Information': 'معلومات',
    'Details': 'تفاصيل',
    'Options': 'خيارات',
    'Preferences': 'تفضيلات',
    'Configuration': 'إعدادات',
    'Setup': 'إعداد',
    'Installation': 'تثبيت',
    'Update': 'تحديث',
    'Upgrade': 'ترقية',
    'Version': 'إصدار',
    'Release': 'إصدار',
    'Build': 'بناء',
    'Development': 'تطوير',
    'Production': 'إنتاج',
    'Testing': 'اختبار',
    'Debug': 'تصحيح',
    'Log': 'سجل',
    'Logs': 'سجلات',
    'History': 'تاريخ',
    'Record': 'سجل',
    'Entry': 'إدخال',
    'Item': 'عنصر',
    'List': 'قائمة',
    'Menu': 'قائمة',
    'Button': 'زر',
    'Text': 'نص',
    'Message': 'رسالة',
    'Notification': 'إشعار',
    'Alert': 'تنبيه',
    'Problem': 'مشكلة',
    'Solution': 'حل',
    'Fix': 'إصلاح',
    'Repair': 'إصلاح',
    'Restore': 'استعادة',
    'Backup': 'نسخة احتياطية',
    'Copy': 'نسخ',
    'Paste': 'لصق',
    'Cut': 'قص',
    'Undo': 'تراجع',
    'Redo': 'إعادة',
    'Select': 'اختيار',
    'Choose': 'اختيار',
    'Pick': 'اختيار',
    'Option': 'خيار',
    'Choice': 'اختيار',
    'Alternative': 'بديل',
    'Variant': 'متغير',
    'Mode': 'وضع',
    'State': 'حالة',
    'Condition': 'شرط',
    'Requirement': 'متطلب',
    'Necessity': 'ضرورة',
    'Need': 'حاجة',
    'Want': 'أريد',
    'Like': 'أحب',
    'Prefer': 'أفضل',
    'Recommend': 'أنصح',
    'Suggest': 'أقترح',
    'Advise': 'أنصح',
    'Tip': 'نصيحة',
    'Hint': 'تلميح',
    'Clue': 'دليل',
    'Guide': 'دليل',
    'Manual': 'دليل',
    'Instructions': 'تعليمات',
    'Steps': 'خطوات',
    'Process': 'عملية',
    'Procedure': 'إجراء',
    'Method': 'طريقة',
    'Way': 'طريقة',
    'Approach': 'نهج',
    'Strategy': 'استراتيجية',
    'Plan': 'خطة',
    'Schedule': 'جدول',
    'Timeline': 'الجدول الزمني',
    'Deadline': 'الموعد النهائي',
    'Due': 'مستحق',
    'Expired': 'منتهي الصلاحية',
    'Valid': 'صالح',
    'Invalid': 'غير صالح',
    'Expired': 'منتهي الصلاحية',
    'Active': 'نشط',
    'Inactive': 'غير نشط',
    'Online': 'متصل',
    'Offline': 'غير متصل',
    'Connected': 'متصل',
    'Disconnected': 'غير متصل',
    'Available': 'متاح',
    'Unavailable': 'غير متاح',
    'Busy': 'مشغول',
    'Free': 'حر',
    'Open': 'مفتوح',
    'Closed': 'مغلق',
    'Locked': 'مقفل',
    'Unlocked': 'مفتوح',
    'Secure': 'آمن',
    'Safe': 'آمن',
    'Dangerous': 'خطير',
    'Risky': 'محفوف بالمخاطر',
    'Important': 'مهم',
    'Critical': 'حرج',
    'Urgent': 'عاجل',
    'Priority': 'أولوية',
    'High': 'عالي',
    'Low': 'منخفض',
    'Medium': 'متوسط',
    'Normal': 'عادي',
    'Standard': 'قياسي',
    'Basic': 'أساسي',
    'Advanced': 'متقدم',
    'Expert': 'خبير',
    'Professional': 'مهني',
    'Beginner': 'مبتدئ',
    'Intermediate': 'متوسط',
    'Expert': 'خبير',
    'User': 'مستخدم',
    'Admin': 'مدير',
    'Moderator': 'مشرف',
    'Guest': 'ضيف',
    'Member': 'عضو',
    'Subscriber': 'مشترك',
    'Customer': 'عميل',
    'Client': 'عميل',
    'Server': 'خادم',
    'Service': 'خدمة',
    'System': 'نظام',
    'Application': 'تطبيق',
    'Program': 'برنامج',
    'Software': 'برمجيات',
    'Hardware': 'أجهزة',
    'Device': 'جهاز',
    'Machine': 'آلة',
    'Computer': 'كمبيوتر',
    'Mobile': 'جوال',
    'Desktop': 'سطح المكتب',
    'Laptop': 'لابتوب',
    'Tablet': 'تابلت',
    'Phone': 'هاتف',
    'Smartphone': 'هاتف ذكي',
    'Browser': 'متصفح',
    'Website': 'موقع ويب',
    'Webpage': 'صفحة ويب',
    'Page': 'صفحة',
    'Site': 'موقع',
    'Domain': 'نطاق',
    'Network': 'شبكة',
    'Internet': 'إنترنت',
    'Connection': 'اتصال',
    'Bandwidth': 'عرض النطاق',
    'Speed': 'سرعة',
    'Latency': 'زمن الاستجابة',
    'Ping': 'بينغ',
    'Timeout': 'انتهاء الوقت',
    'Retry': 'إعادة المحاولة',
    'Attempt': 'محاولة',
    'Trial': 'محاولة',
    'Test': 'اختبار',
    'Check': 'فحص',
    'Verify': 'التحقق',
    'Validate': 'التحقق من الصحة',
    'Confirm': 'تأكيد',
    'Approve': 'موافقة',
    'Reject': 'رفض',
    'Accept': 'قبول',
    'Decline': 'رفض',
    'Allow': 'السماح',
    'Deny': 'رفض',
    'Block': 'حظر',
    'Unblock': 'إلغاء الحظر',
    'Enable': 'تفعيل',
    'Disable': 'إلغاء التفعيل',
    'Activate': 'تفعيل',
    'Deactivate': 'إلغاء التفعيل',
    'Start': 'بدء',
    'Stop': 'إيقاف',
    'Pause': 'إيقاف مؤقت',
    'Resume': 'متابعة',
    'Restart': 'إعادة تشغيل',
    'Reload': 'إعادة تحميل',
    'Refresh': 'تحديث',
    'Update': 'تحديث',
    'Upgrade': 'ترقية',
    'Downgrade': 'تخفيض',
    'Install': 'تثبيت',
    'Uninstall': 'إلغاء التثبيت',
    'Remove': 'إزالة',
    'Delete': 'حذف',
    'Clear': 'مسح',
    'Reset': 'إعادة تعيين',
    'Restore': 'استعادة',
    'Backup': 'نسخة احتياطية',
    'Recover': 'استعادة',
    'Repair': 'إصلاح',
    'Fix': 'إصلاح',
    'Solve': 'حل',
    'Resolve': 'حل',
    'Handle': 'معالجة',
    'Process': 'معالجة',
    'Execute': 'تنفيذ',
    'Run': 'تشغيل',
    'Launch': 'إطلاق',
    'Open': 'فتح',
    'Close': 'إغلاق',
    'Exit': 'خروج',
    'Quit': 'خروج',
    'End': 'نهاية',
    'Finish': 'إنهاء',
    'Complete': 'إكمال',
    'Done': 'تم',
    'Ready': 'جاهز',
    'Available': 'متاح',
    'Unavailable': 'غير متاح',
    'Online': 'متصل',
    'Offline': 'غير متصل',
    'Connected': 'متصل',
    'Disconnected': 'غير متصل',
    'Active': 'نشط',
    'Inactive': 'غير نشط',
    'Enabled': 'مفعل',
    'Disabled': 'معطل',
    'On': 'تشغيل',
    'Off': 'إيقاف',
    'Yes': 'نعم',
    'No': 'لا',
    'True': 'صحيح',
    'False': 'خطأ',
    'Null': 'فارغ',
    'Empty': 'فارغ',
    'Full': 'ممتلئ',
    'Partial': 'جزئي',
    'Complete': 'مكتمل',
    'Incomplete': 'غير مكتمل',
    'Valid': 'صالح',
    'Invalid': 'غير صالح',
    'Expired': 'منتهي الصلاحية',
    'Correct': 'صحيح',
    'Incorrect': 'غير صحيح',
    'Right': 'صحيح',
    'Wrong': 'خطأ',
    'Good': 'جيد',
    'Bad': 'سيء',
    'Better': 'أفضل',
    'Worse': 'أسوأ',
    'Best': 'الأفضل',
    'Worst': 'الأسوأ',
    'New': 'جديد',
    'Old': 'قديم',
    'Recent': 'حديث',
    'Latest': 'الأحدث',
    'Current': 'الحالي',
    'Previous': 'السابق',
    'Next': 'التالي',
    'First': 'الأول',
    'Last': 'الأخير',
    'Second': 'الثاني',
    'Third': 'الثالث',
    'Fourth': 'الرابع',
    'Fifth': 'الخامس',
    'Sixth': 'السادس',
    'Seventh': 'السابع',
    'Eighth': 'الثامن',
    'Ninth': 'التاسع',
    'Tenth': 'العاشر',
    'One': 'واحد',
    'Two': 'اثنان',
    'Three': 'ثلاثة',
    'Four': 'أربعة',
    'Five': 'خمسة',
    'Six': 'ستة',
    'Seven': 'سبعة',
    'Eight': 'ثمانية',
    'Nine': 'تسعة',
    'Ten': 'عشرة',
    'Eleven': 'أحد عشر',
    'Twelve': 'اثنا عشر',
    'Thirteen': 'ثلاثة عشر',
    'Fourteen': 'أربعة عشر',
    'Fifteen': 'خمسة عشر',
    'Sixteen': 'ستة عشر',
    'Seventeen': 'سبعة عشر',
    'Eighteen': 'ثمانية عشر',
    'Nineteen': 'تسعة عشر',
    'Twenty': 'عشرون',
    'Thirty': 'ثلاثون',
    'Forty': 'أربعون',
    'Fifty': 'خمسون',
    'Sixty': 'ستون',
    'Seventy': 'سبعون',
    'Eighty': 'ثمانون',
    'Ninety': 'تسعون',
    'Hundred': 'مائة',
    'Thousand': 'ألف',
    'Million': 'مليون',
    'Billion': 'مليار',
    'Trillion': 'تريليون',
    'Zero': 'صفر',
    'None': 'لا شيء',
    'All': 'الكل',
    'Some': 'بعض',
    'Many': 'كثير',
    'Few': 'قليل',
    'Little': 'قليل',
    'Much': 'كثير',
    'More': 'أكثر',
    'Less': 'أقل',
    'Most': 'معظم',
    'Least': 'الأقل',
    'Enough': 'كافي',
    'Too much': 'كثير جداً',
    'Too little': 'قليل جداً',
    'Too many': 'كثير جداً',
    'Too few': 'قليل جداً',
    'Very': 'جداً',
    'Quite': 'تماماً',
    'Rather': 'بدلاً من',
    'Pretty': 'جميل',
    'Fairly': 'عادل',
    'Somewhat': 'إلى حد ما',
    'Slightly': 'قليلاً',
    'Hardly': 'بالكاد',
    'Barely': 'بالكاد',
    'Almost': 'تقريباً',
    'Nearly': 'تقريباً',
    'About': 'حول',
    'Around': 'حول',
    'Approximately': 'تقريباً',
    'Exactly': 'بالضبط',
    'Precisely': 'بدقة',
    'Roughly': 'تقريباً',
    'Nearly': 'تقريباً',
    'Almost': 'تقريباً',
    'Just': 'فقط',
    'Only': 'فقط',
    'Even': 'حتى',
    'Still': 'لا يزال',
    'Yet': 'بعد',
    'Already': 'بالفعل',
    'Soon': 'قريباً',
    'Later': 'لاحقاً',
    'Earlier': 'سابقاً',
    'Before': 'قبل',
    'After': 'بعد',
    'During': 'أثناء',
    'While': 'بينما',
    'Since': 'منذ',
    'Until': 'حتى',
    'From': 'من',
    'To': 'إلى',
    'At': 'في',
    'In': 'في',
    'On': 'على',
    'Under': 'تحت',
    'Over': 'فوق',
    'Above': 'أعلى',
    'Below': 'أدنى',
    'Between': 'بين',
    'Among': 'بين',
    'Through': 'عبر',
    'Across': 'عبر',
    'Along': 'على طول',
    'Around': 'حول',
    'Behind': 'خلف',
    'Beside': 'بجانب',
    'Near': 'قريب',
    'Far': 'بعيد',
    'Close': 'قريب',
    'Distant': 'بعيد',
    'Local': 'محلي',
    'Remote': 'بعيد',
    'Global': 'عالمي',
    'International': 'دولي',
    'National': 'وطني',
    'Regional': 'إقليمي',
    'Local': 'محلي',
    'Public': 'عام',
    'Private': 'خاص',
    'Personal': 'شخصي',
    'Individual': 'فردي',
    'Group': 'مجموعة',
    'Team': 'فريق',
    'Organization': 'منظمة',
    'Company': 'شركة',
    'Business': 'أعمال',
    'Enterprise': 'مؤسسة',
    'Corporation': 'شركة',
    'Firm': 'شركة',
    'Office': 'مكتب',
    'Department': 'قسم',
    'Division': 'قسم',
    'Section': 'قسم',
    'Unit': 'وحدة',
    'Part': 'جزء',
    'Piece': 'قطعة',
    'Bit': 'بت',
    'Byte': 'بايت',
    'Kilobyte': 'كيلوبايت',
    'Megabyte': 'ميجابايت',
    'Gigabyte': 'جيجابايت',
    'Terabyte': 'تيرابايت',
    'Petabyte': 'بيتابايت',
    'Exabyte': 'إكسابايت',
    'Zettabyte': 'زيتابايت',
    'Yottabyte': 'يوتابايت',
    'Bit': 'بت',
    'Byte': 'بايت',
    'Word': 'كلمة',
    'Character': 'حرف',
    'String': 'سلسلة',
    'Text': 'نص',
    'Data': 'بيانات',
    'Information': 'معلومات',
    'Content': 'محتوى',
    'Material': 'مادة',
    'Substance': 'مادة',
    'Matter': 'مادة',
    'Object': 'كائن',
    'Subject': 'موضوع',
    'Topic': 'موضوع',
    'Theme': 'موضوع',
    'Subject': 'موضوع',
    'Issue': 'قضية',
    'Problem': 'مشكلة',
    'Question': 'سؤال',
    'Answer': 'إجابة',
    'Reply': 'رد',
    'Response': 'استجابة',
    'Reaction': 'تفاعل',
    'Feedback': 'تعليقات',
    'Comment': 'تعليق',
    'Note': 'ملاحظة',
    'Remark': 'ملاحظة',
    'Observation': 'ملاحظة',
    'Opinion': 'رأي',
    'View': 'رأي',
    'Perspective': 'منظور',
    'Aspect': 'جانب',
    'Side': 'جانب',
    'Part': 'جزء',
    'Component': 'مكون',
    'Element': 'عنصر',
    'Factor': 'عامل',
    'Feature': 'ميزة',
    'Characteristic': 'خاصية',
    'Property': 'خاصية',
    'Attribute': 'صفة',
    'Quality': 'جودة',
    'Value': 'قيمة',
    'Amount': 'مبلغ',
    'Quantity': 'كمية',
    'Number': 'رقم',
    'Count': 'عدد',
    'Total': 'المجموع',
    'Sum': 'مجموع',
    'Average': 'متوسط',
    'Mean': 'متوسط',
    'Median': 'متوسط',
    'Mode': 'وضع',
    'Range': 'نطاق',
    'Minimum': 'الحد الأدنى',
    'Maximum': 'الحد الأقصى',
    'Limit': 'حد',
    'Boundary': 'حدود',
    'Edge': 'حافة',
    'Border': 'حدود',
    'Margin': 'هامش',
    'Padding': 'حشو',
    'Space': 'مساحة',
    'Gap': 'فجوة',
    'Distance': 'مسافة',
    'Length': 'طول',
    'Width': 'عرض',
    'Height': 'ارتفاع',
    'Depth': 'عمق',
    'Thickness': 'سمك',
    'Size': 'حجم',
    'Dimension': 'بعد',
    'Area': 'منطقة',
    'Volume': 'حجم',
    'Weight': 'وزن',
    'Mass': 'كتلة',
    'Density': 'كثافة',
    'Speed': 'سرعة',
    'Velocity': 'سرعة',
    'Acceleration': 'تسارع',
    'Force': 'قوة',
    'Power': 'قوة',
    'Energy': 'طاقة',
    'Work': 'عمل',
    'Time': 'وقت',
    'Duration': 'مدة',
    'Period': 'فترة',
    'Interval': 'فترة',
    'Frequency': 'تردد',
    'Rate': 'معدل',
    'Ratio': 'نسبة',
    'Percentage': 'نسبة مئوية',
    'Proportion': 'نسبة',
    'Fraction': 'كسر',
    'Decimal': 'عشري',
    'Integer': 'عدد صحيح',
    'Float': 'عائم',
    'Double': 'مزدوج',
    'Boolean': 'منطقي',
    'String': 'سلسلة',
    'Array': 'مصفوفة',
    'List': 'قائمة',
    'Set': 'مجموعة',
    'Map': 'خريطة',
    'Dictionary': 'قاموس',
    'Table': 'جدول',
    'Row': 'صف',
    'Column': 'عمود',
    'Cell': 'خلية',
    'Field': 'حقل',
    'Record': 'سجل',
    'Entry': 'إدخال',
    'Item': 'عنصر',
    'Node': 'عقدة',
    'Vertex': 'رأس',
    'Edge': 'حافة',
    'Graph': 'رسم بياني',
    'Tree': 'شجرة',
    'Forest': 'غابة',
    'Network': 'شبكة',
    'Grid': 'شبكة',
    'Matrix': 'مصفوفة',
    'Vector': 'متجه',
    'Point': 'نقطة',
    'Line': 'خط',
    'Curve': 'منحنى',
    'Surface': 'سطح',
    'Plane': 'طائرة',
    'Space': 'فضاء',
    'Dimension': 'بعد',
    'Axis': 'محور',
    'Coordinate': 'إحداثي',
    'Position': 'موضع',
    'Location': 'موقع',
    'Place': 'مكان',
    'Spot': 'بقعة',
    'Point': 'نقطة',
    'Area': 'منطقة',
    'Region': 'منطقة',
    'Zone': 'منطقة',
    'Territory': 'إقليم',
    'Country': 'دولة',
    'State': 'ولاية',
    'Province': 'مقاطعة',
    'City': 'مدينة',
    'Town': 'بلدة',
    'Village': 'قرية',
    'Street': 'شارع',
    'Road': 'طريق',
    'Path': 'مسار',
    'Route': 'طريق',
    'Way': 'طريقة',
    'Direction': 'اتجاه',
    'Course': 'مسار',
    'Bearing': 'اتجاه',
    'Heading': 'عنوان',
    'Orientation': 'اتجاه',
    'Alignment': 'محاذاة'
}

def translate_text(text, translations):
    """Переводит текст используя словарь переводов"""
    if not text or not isinstance(text, str):
        return text
    
    # Исключаем строки с плейсхолдерами и техническими переменными
    exclude_patterns = [
        r'\{[^}]+\}',  # {variable}, {error}, {attempt} и т.д.
        r'FIREBASE_',  # FIREBASE_CONF, FIREBASE_USER и т.д.
        r'Config\.',   # Config.BOT_NAME и т.д.
        r'@[a-zA-Z_]+',  # @username, @bot_name и т.д.
        r'https?://',  # URL
        r'<[^>]+>',    # HTML теги
        r'`[^`]+`',    # Код в backticks
        r'[A-Z_]+_[A-Z_]+',  # Константы типа ERROR_MSG
    ]
    
    # Проверяем, содержит ли строка исключаемые паттерны
    for pattern in exclude_patterns:
        if re.search(pattern, text):
            return text  # Не переводим
    
    # Простой поиск и замена
    result = text
    for english, arabic in translations.items():
        # Заменяем только целые слова, но не внутри фигурных скобок
        pattern = r'\b' + re.escape(english) + r'\b'
        result = re.sub(pattern, arabic, result, flags=re.IGNORECASE)
    
    return result

def translate_messages_file(file_path, translations):
    """Переводит файл сообщений"""
    if not os.path.exists(file_path):
        print(f"Файл не найден: {file_path}")
        return
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Находим все строки с переменными (более точный паттерн)
    pattern = r'(\w+_MSG) = "([^"]*(?:\\.[^"]*)*)"'
    matches = re.findall(pattern, content)
    
    translated_count = 0
    for var_name, text in matches:
        # Пропускаем технические переменные
        if any(tech in var_name for tech in ['FIREBASE_', 'Config.', 'ADMIN_', 'DB_', 'MAGIC_']):
            continue
            
        # Пропускаем переменные с плейсхолдерами
        if re.search(r'\{[^}]+\}', text):
            continue
            
        translated_text = translate_text(text, translations)
        if translated_text != text:
            # Заменяем в содержимом
            old_line = f'{var_name} = "{text}"'
            new_line = f'{var_name} = "{translated_text}"'
            content = content.replace(old_line, new_line)
            translated_count += 1
            print(f"Переведено: {var_name}")
    
    # Сохраняем переведенный файл
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"Переведено {translated_count} переменных в {file_path}")

if __name__ == "__main__":
    # Переводим арабский файл
    ar_file = "/mnt/c/Users/chelaxian/Desktop/tg-ytdlp-NEW/CONFIG/LANGUAGES/messages_AR.py"
    translate_messages_file(ar_file, AR_TRANSLATIONS)
