#!/usr/bin/env python3
"""
Перевод хинди файла сообщений
"""

import re
import os

# Хинди переводы
IN_TRANSLATIONS = {
    'Downloading': 'डाउनलोड हो रहा है',
    'Processing': 'प्रसंस्करण हो रहा है', 
    'Complete': 'पूर्ण',
    'Error': 'त्रुटि',
    'Failed': 'असफल',
    'Success': 'सफल',
    'Warning': 'चेतावनी',
    'Settings': 'सेटिंग्स',
    'Help': 'सहायता',
    'Close': 'बंद करें',
    'Back': 'वापस',
    'Next': 'अगला',
    'Cancel': 'रद्द करें',
    'Confirm': 'पुष्टि करें',
    'Save': 'सहेजें',
    'Delete': 'हटाएं',
    'Edit': 'संपादित करें',
    'Add': 'जोड़ें',
    'Remove': 'हटाएं',
    'Update': 'अपडेट करें',
    'Refresh': 'रिफ्रेश करें',
    'Search': 'खोजें',
    'Filter': 'फिल्टर',
    'Sort': 'क्रमबद्ध करें',
    'Download': 'डाउनलोड',
    'Upload': 'अपलोड',
    'Send': 'भेजें',
    'Receive': 'प्राप्त करें',
    'Start': 'शुरू करें',
    'Stop': 'रोकें',
    'Pause': 'रोकें',
    'Resume': 'जारी रखें',
    'Retry': 'पुनः प्रयास करें',
    'Continue': 'जारी रखें',
    'Finish': 'समाप्त करें',
    'Done': 'हो गया',
    'Ready': 'तैयार',
    'Loading': 'लोड हो रहा है',
    'Waiting': 'प्रतीक्षा',
    'Please wait': 'कृपया प्रतीक्षा करें',
    'Please try again': 'कृपया पुनः प्रयास करें',
    'Try again': 'पुनः प्रयास करें',
    'Invalid': 'अमान्य',
    'Valid': 'मान्य',
    'Available': 'उपलब्ध',
    'Unavailable': 'अनुपलब्ध',
    'Enabled': 'सक्षम',
    'Disabled': 'अक्षम',
    'On': 'चालू',
    'Off': 'बंद',
    'Yes': 'हाँ',
    'No': 'नहीं',
    'OK': 'ठीक है',
    'Apply': 'लागू करें',
    'Reset': 'रीसेट करें',
    'Default': 'डिफ़ॉल्ट',
    'Custom': 'कस्टम',
    'Auto': 'ऑटो',
    'Manual': 'मैनुअल',
    'Automatic': 'स्वचालित',
    'Quality': 'गुणवत्ता',
    'Format': 'प्रारूप',
    'Size': 'आकार',
    'Duration': 'अवधि',
    'Title': 'शीर्षक',
    'Description': 'विवरण',
    'Name': 'नाम',
    'Type': 'प्रकार',
    'Status': 'स्थिति',
    'Progress': 'प्रगति',
    'Speed': 'गति',
    'Time': 'समय',
    'Date': 'तारीख',
    'File': 'फ़ाइल',
    'Folder': 'फ़ोल्डर',
    'Directory': 'निर्देशिका',
    'Path': 'पथ',
    'URL': 'यूआरएल',
    'Link': 'लिंक',
    'Video': 'वीडियो',
    'Audio': 'ऑडियो',
    'Image': 'छवि',
    'Photo': 'फोटो',
    'Picture': 'तस्वीर',
    'Media': 'मीडिया',
    'Content': 'सामग्री',
    'Data': 'डेटा',
    'Information': 'जानकारी',
    'Details': 'विवरण',
    'Options': 'विकल्प',
    'Preferences': 'प्राथमिकताएं',
    'Configuration': 'कॉन्फ़िगरेशन',
    'Setup': 'सेटअप',
    'Installation': 'स्थापना',
    'Update': 'अपडेट',
    'Upgrade': 'अपग्रेड',
    'Version': 'संस्करण',
    'Release': 'रिलीज़',
    'Build': 'बिल्ड',
    'Development': 'विकास',
    'Production': 'उत्पादन',
    'Testing': 'परीक्षण',
    'Debug': 'डिबग',
    'Log': 'लॉग',
    'Logs': 'लॉग्स',
    'History': 'इतिहास',
    'Record': 'रिकॉर्ड',
    'Entry': 'प्रविष्टि',
    'Item': 'आइटम',
    'List': 'सूची',
    'Menu': 'मेनू',
    'Button': 'बटन',
    'Text': 'टेक्स्ट',
    'Message': 'संदेश',
    'Notification': 'सूचना',
    'Alert': 'अलर्ट',
    'Problem': 'समस्या',
    'Solution': 'समाधान',
    'Fix': 'ठीक करें',
    'Repair': 'मरम्मत',
    'Restore': 'पुनर्स्थापित करें',
    'Backup': 'बैकअप',
    'Copy': 'कॉपी',
    'Paste': 'पेस्ट',
    'Cut': 'कट',
    'Undo': 'पूर्ववत करें',
    'Redo': 'फिर से करें',
    'Select': 'चुनें',
    'Choose': 'चुनें',
    'Pick': 'चुनें',
    'Option': 'विकल्प',
    'Choice': 'विकल्प',
    'Alternative': 'विकल्प',
    'Variant': 'वेरिएंट',
    'Mode': 'मोड',
    'State': 'स्थिति',
    'Condition': 'शर्त',
    'Requirement': 'आवश्यकता',
    'Necessity': 'आवश्यकता',
    'Need': 'आवश्यकता',
    'Want': 'चाहते हैं',
    'Like': 'पसंद',
    'Prefer': 'पसंद',
    'Recommend': 'सुझाव',
    'Suggest': 'सुझाव',
    'Advise': 'सलाह',
    'Tip': 'टिप',
    'Hint': 'संकेत',
    'Clue': 'सुराग',
    'Guide': 'गाइड',
    'Manual': 'मैनुअल',
    'Instructions': 'निर्देश',
    'Steps': 'चरण',
    'Process': 'प्रक्रिया',
    'Procedure': 'प्रक्रिया',
    'Method': 'विधि',
    'Way': 'तरीका',
    'Approach': 'दृष्टिकोण',
    'Strategy': 'रणनीति',
    'Plan': 'योजना',
    'Schedule': 'अनुसूची',
    'Timeline': 'समयरेखा',
    'Deadline': 'अंतिम तिथि',
    'Due': 'देय',
    'Expired': 'समाप्त',
    'Valid': 'मान्य',
    'Invalid': 'अमान्य',
    'Expired': 'समाप्त',
    'Active': 'सक्रिय',
    'Inactive': 'निष्क्रिय',
    'Online': 'ऑनलाइन',
    'Offline': 'ऑफलाइन',
    'Connected': 'जुड़ा हुआ',
    'Disconnected': 'डिस्कनेक्ट',
    'Available': 'उपलब्ध',
    'Unavailable': 'अनुपलब्ध',
    'Busy': 'व्यस्त',
    'Free': 'मुफ्त',
    'Open': 'खुला',
    'Closed': 'बंद',
    'Locked': 'लॉक',
    'Unlocked': 'अनलॉक',
    'Secure': 'सुरक्षित',
    'Safe': 'सुरक्षित',
    'Dangerous': 'खतरनाक',
    'Risky': 'जोखिम भरा',
    'Important': 'महत्वपूर्ण',
    'Critical': 'गंभीर',
    'Urgent': 'तत्काल',
    'Priority': 'प्राथमिकता',
    'High': 'उच्च',
    'Low': 'निम्न',
    'Medium': 'मध्यम',
    'Normal': 'सामान्य',
    'Standard': 'मानक',
    'Basic': 'बुनियादी',
    'Advanced': 'उन्नत',
    'Expert': 'विशेषज्ञ',
    'Professional': 'पेशेवर',
    'Beginner': 'शुरुआती',
    'Intermediate': 'मध्यवर्ती',
    'Expert': 'विशेषज्ञ',
    'User': 'उपयोगकर्ता',
    'Admin': 'एडमिन',
    'Moderator': 'मॉडरेटर',
    'Guest': 'अतिथि',
    'Member': 'सदस्य',
    'Subscriber': 'सब्सक्राइबर',
    'Customer': 'ग्राहक',
    'Client': 'क्लाइंट',
    'Server': 'सर्वर',
    'Service': 'सेवा',
    'System': 'सिस्टम',
    'Application': 'एप्लिकेशन',
    'Program': 'प्रोग्राम',
    'Software': 'सॉफ्टवेयर',
    'Hardware': 'हार्डवेयर',
    'Device': 'डिवाइस',
    'Machine': 'मशीन',
    'Computer': 'कंप्यूटर',
    'Mobile': 'मोबाइल',
    'Desktop': 'डेस्कटॉप',
    'Laptop': 'लैपटॉप',
    'Tablet': 'टैबलेट',
    'Phone': 'फोन',
    'Smartphone': 'स्मार्टफोन',
    'Browser': 'ब्राउज़र',
    'Website': 'वेबसाइट',
    'Webpage': 'वेबपेज',
    'Page': 'पेज',
    'Site': 'साइट',
    'Domain': 'डोमेन',
    'Network': 'नेटवर्क',
    'Internet': 'इंटरनेट',
    'Connection': 'कनेक्शन',
    'Bandwidth': 'बैंडविड्थ',
    'Speed': 'गति',
    'Latency': 'लेटेंसी',
    'Ping': 'पिंग',
    'Timeout': 'टाइमआउट',
    'Retry': 'पुनः प्रयास',
    'Attempt': 'प्रयास',
    'Trial': 'परीक्षण',
    'Test': 'टेस्ट',
    'Check': 'जांच',
    'Verify': 'सत्यापित करें',
    'Validate': 'मान्य करें',
    'Confirm': 'पुष्टि करें',
    'Approve': 'अनुमोदन',
    'Reject': 'अस्वीकार',
    'Accept': 'स्वीकार',
    'Decline': 'अस्वीकार',
    'Allow': 'अनुमति',
    'Deny': 'अस्वीकार',
    'Block': 'ब्लॉक',
    'Unblock': 'अनब्लॉक',
    'Enable': 'सक्षम करें',
    'Disable': 'अक्षम करें',
    'Activate': 'सक्रिय करें',
    'Deactivate': 'निष्क्रिय करें',
    'Start': 'शुरू करें',
    'Stop': 'रोकें',
    'Pause': 'रोकें',
    'Resume': 'जारी रखें',
    'Restart': 'पुनः आरंभ',
    'Reload': 'रिलोड',
    'Refresh': 'रिफ्रेश',
    'Update': 'अपडेट',
    'Upgrade': 'अपग्रेड',
    'Downgrade': 'डाउनग्रेड',
    'Install': 'इंस्टॉल',
    'Uninstall': 'अनइंस्टॉल',
    'Remove': 'हटाएं',
    'Delete': 'हटाएं',
    'Clear': 'साफ करें',
    'Reset': 'रीसेट',
    'Restore': 'पुनर्स्थापित करें',
    'Backup': 'बैकअप',
    'Recover': 'पुनर्प्राप्त करें',
    'Repair': 'मरम्मत',
    'Fix': 'ठीक करें',
    'Solve': 'हल करें',
    'Resolve': 'हल करें',
    'Handle': 'संभालें',
    'Process': 'प्रक्रिया',
    'Execute': 'निष्पादित करें',
    'Run': 'चलाएं',
    'Launch': 'लॉन्च करें',
    'Open': 'खोलें',
    'Close': 'बंद करें',
    'Exit': 'बाहर निकलें',
    'Quit': 'छोड़ें',
    'End': 'अंत',
    'Finish': 'समाप्त करें',
    'Complete': 'पूर्ण करें',
    'Done': 'हो गया',
    'Ready': 'तैयार',
    'Available': 'उपलब्ध',
    'Unavailable': 'अनुपलब्ध',
    'Online': 'ऑनलाइन',
    'Offline': 'ऑफलाइन',
    'Connected': 'जुड़ा हुआ',
    'Disconnected': 'डिस्कनेक्ट',
    'Active': 'सक्रिय',
    'Inactive': 'निष्क्रिय',
    'Enabled': 'सक्षम',
    'Disabled': 'अक्षम',
    'On': 'चालू',
    'Off': 'बंद',
    'Yes': 'हाँ',
    'No': 'नहीं',
    'True': 'सत्य',
    'False': 'असत्य',
    'Null': 'शून्य',
    'Empty': 'खाली',
    'Full': 'भरा हुआ',
    'Partial': 'आंशिक',
    'Complete': 'पूर्ण',
    'Incomplete': 'अपूर्ण',
    'Valid': 'मान्य',
    'Invalid': 'अमान्य',
    'Expired': 'समाप्त',
    'Correct': 'सही',
    'Incorrect': 'गलत',
    'Right': 'सही',
    'Wrong': 'गलत',
    'Good': 'अच्छा',
    'Bad': 'बुरा',
    'Better': 'बेहतर',
    'Worse': 'बदतर',
    'Best': 'सबसे अच्छा',
    'Worst': 'सबसे बुरा',
    'New': 'नया',
    'Old': 'पुराना',
    'Recent': 'हाल का',
    'Latest': 'नवीनतम',
    'Current': 'वर्तमान',
    'Previous': 'पिछला',
    'Next': 'अगला',
    'First': 'पहला',
    'Last': 'अंतिम',
    'Second': 'दूसरा',
    'Third': 'तीसरा',
    'Fourth': 'चौथा',
    'Fifth': 'पांचवां',
    'Sixth': 'छठा',
    'Seventh': 'सातवां',
    'Eighth': 'आठवां',
    'Ninth': 'नौवां',
    'Tenth': 'दसवां',
    'One': 'एक',
    'Two': 'दो',
    'Three': 'तीन',
    'Four': 'चार',
    'Five': 'पांच',
    'Six': 'छह',
    'Seven': 'सात',
    'Eight': 'आठ',
    'Nine': 'नौ',
    'Ten': 'दस',
    'Eleven': 'ग्यारह',
    'Twelve': 'बारह',
    'Thirteen': 'तेरह',
    'Fourteen': 'चौदह',
    'Fifteen': 'पंद्रह',
    'Sixteen': 'सोलह',
    'Seventeen': 'सत्रह',
    'Eighteen': 'अठारह',
    'Nineteen': 'उन्नीस',
    'Twenty': 'बीस',
    'Thirty': 'तीस',
    'Forty': 'चालीस',
    'Fifty': 'पचास',
    'Sixty': 'साठ',
    'Seventy': 'सत्तर',
    'Eighty': 'अस्सी',
    'Ninety': 'नब्बे',
    'Hundred': 'सौ',
    'Thousand': 'हजार',
    'Million': 'लाख',
    'Billion': 'अरब',
    'Trillion': 'खरब',
    'Zero': 'शून्य',
    'None': 'कोई नहीं',
    'All': 'सभी',
    'Some': 'कुछ',
    'Many': 'कई',
    'Few': 'कुछ',
    'Little': 'थोड़ा',
    'Much': 'बहुत',
    'More': 'अधिक',
    'Less': 'कम',
    'Most': 'अधिकांश',
    'Least': 'कम से कम',
    'Enough': 'पर्याप्त',
    'Too much': 'बहुत अधिक',
    'Too little': 'बहुत कम',
    'Too many': 'बहुत अधिक',
    'Too few': 'बहुत कम',
    'Very': 'बहुत',
    'Quite': 'काफी',
    'Rather': 'बल्कि',
    'Pretty': 'सुंदर',
    'Fairly': 'निष्पक्ष',
    'Somewhat': 'कुछ हद तक',
    'Slightly': 'थोड़ा',
    'Hardly': 'मुश्किल से',
    'Barely': 'मुश्किल से',
    'Almost': 'लगभग',
    'Nearly': 'लगभग',
    'About': 'के बारे में',
    'Around': 'आसपास',
    'Approximately': 'लगभग',
    'Exactly': 'बिल्कुल',
    'Precisely': 'सटीक',
    'Roughly': 'लगभग',
    'Nearly': 'लगभग',
    'Almost': 'लगभग',
    'Just': 'बस',
    'Only': 'केवल',
    'Even': 'भी',
    'Still': 'अभी भी',
    'Yet': 'अभी तक',
    'Already': 'पहले से',
    'Soon': 'जल्दी',
    'Later': 'बाद में',
    'Earlier': 'पहले',
    'Before': 'पहले',
    'After': 'बाद में',
    'During': 'दौरान',
    'While': 'जबकि',
    'Since': 'से',
    'Until': 'तक',
    'From': 'से',
    'To': 'को',
    'At': 'पर',
    'In': 'में',
    'On': 'पर',
    'Under': 'नीचे',
    'Over': 'ऊपर',
    'Above': 'ऊपर',
    'Below': 'नीचे',
    'Between': 'बीच में',
    'Among': 'के बीच',
    'Through': 'के माध्यम से',
    'Across': 'पार',
    'Along': 'साथ',
    'Around': 'आसपास',
    'Behind': 'पीछे',
    'Beside': 'बगल में',
    'Near': 'पास',
    'Far': 'दूर',
    'Close': 'पास',
    'Distant': 'दूर',
    'Local': 'स्थानीय',
    'Remote': 'दूरस्थ',
    'Global': 'वैश्विक',
    'International': 'अंतर्राष्ट्रीय',
    'National': 'राष्ट्रीय',
    'Regional': 'क्षेत्रीय',
    'Local': 'स्थानीय',
    'Public': 'सार्वजनिक',
    'Private': 'निजी',
    'Personal': 'व्यक्तिगत',
    'Individual': 'व्यक्तिगत',
    'Group': 'समूह',
    'Team': 'टीम',
    'Organization': 'संगठन',
    'Company': 'कंपनी',
    'Business': 'व्यवसाय',
    'Enterprise': 'उद्यम',
    'Corporation': 'निगम',
    'Firm': 'फर्म',
    'Office': 'कार्यालय',
    'Department': 'विभाग',
    'Division': 'विभाग',
    'Section': 'अनुभाग',
    'Unit': 'इकाई',
    'Part': 'भाग',
    'Piece': 'टुकड़ा',
    'Bit': 'बिट',
    'Byte': 'बाइट',
    'Kilobyte': 'किलोबाइट',
    'Megabyte': 'मेगाबाइट',
    'Gigabyte': 'गीगाबाइट',
    'Terabyte': 'टेराबाइट',
    'Petabyte': 'पेटाबाइट',
    'Exabyte': 'एक्साबाइट',
    'Zettabyte': 'जेटाबाइट',
    'Yottabyte': 'योटाबाइट',
    'Bit': 'बिट',
    'Byte': 'बाइट',
    'Word': 'शब्द',
    'Character': 'वर्ण',
    'String': 'स्ट्रिंग',
    'Text': 'टेक्स्ट',
    'Data': 'डेटा',
    'Information': 'जानकारी',
    'Content': 'सामग्री',
    'Material': 'सामग्री',
    'Substance': 'पदार्थ',
    'Matter': 'मामला',
    'Object': 'वस्तु',
    'Subject': 'विषय',
    'Topic': 'विषय',
    'Theme': 'थीम',
    'Subject': 'विषय',
    'Issue': 'मुद्दा',
    'Problem': 'समस्या',
    'Question': 'प्रश्न',
    'Answer': 'उत्तर',
    'Reply': 'जवाब',
    'Response': 'प्रतिक्रिया',
    'Reaction': 'प्रतिक्रिया',
    'Feedback': 'फीडबैक',
    'Comment': 'टिप्पणी',
    'Note': 'नोट',
    'Remark': 'टिप्पणी',
    'Observation': 'अवलोकन',
    'Opinion': 'राय',
    'View': 'दृश्य',
    'Perspective': 'दृष्टिकोण',
    'Aspect': 'पहलू',
    'Side': 'पक्ष',
    'Part': 'भाग',
    'Component': 'घटक',
    'Element': 'तत्व',
    'Factor': 'कारक',
    'Feature': 'सुविधा',
    'Characteristic': 'विशेषता',
    'Property': 'गुण',
    'Attribute': 'गुण',
    'Quality': 'गुणवत्ता',
    'Value': 'मूल्य',
    'Amount': 'राशि',
    'Quantity': 'मात्रा',
    'Number': 'संख्या',
    'Count': 'गिनती',
    'Total': 'कुल',
    'Sum': 'योग',
    'Average': 'औसत',
    'Mean': 'माध्य',
    'Median': 'माध्यिका',
    'Mode': 'बहुलक',
    'Range': 'सीमा',
    'Minimum': 'न्यूनतम',
    'Maximum': 'अधिकतम',
    'Limit': 'सीमा',
    'Boundary': 'सीमा',
    'Edge': 'किनारा',
    'Border': 'सीमा',
    'Margin': 'मार्जिन',
    'Padding': 'पैडिंग',
    'Space': 'स्थान',
    'Gap': 'अंतर',
    'Distance': 'दूरी',
    'Length': 'लंबाई',
    'Width': 'चौड़ाई',
    'Height': 'ऊंचाई',
    'Depth': 'गहराई',
    'Thickness': 'मोटाई',
    'Size': 'आकार',
    'Dimension': 'आयाम',
    'Area': 'क्षेत्र',
    'Volume': 'आयतन',
    'Weight': 'वजन',
    'Mass': 'द्रव्यमान',
    'Density': 'घनत्व',
    'Speed': 'गति',
    'Velocity': 'वेग',
    'Acceleration': 'त्वरण',
    'Force': 'बल',
    'Power': 'शक्ति',
    'Energy': 'ऊर्जा',
    'Work': 'काम',
    'Time': 'समय',
    'Duration': 'अवधि',
    'Period': 'अवधि',
    'Interval': 'अंतराल',
    'Frequency': 'आवृत्ति',
    'Rate': 'दर',
    'Ratio': 'अनुपात',
    'Percentage': 'प्रतिशत',
    'Proportion': 'अनुपात',
    'Fraction': 'भिन्न',
    'Decimal': 'दशमलव',
    'Integer': 'पूर्णांक',
    'Float': 'फ्लोट',
    'Double': 'डबल',
    'Boolean': 'बूलियन',
    'String': 'स्ट्रिंग',
    'Array': 'सरणी',
    'List': 'सूची',
    'Set': 'सेट',
    'Map': 'मैप',
    'Dictionary': 'शब्दकोश',
    'Table': 'तालिका',
    'Row': 'पंक्ति',
    'Column': 'स्तंभ',
    'Cell': 'सेल',
    'Field': 'फील्ड',
    'Record': 'रिकॉर्ड',
    'Entry': 'प्रविष्टि',
    'Item': 'आइटम',
    'Node': 'नोड',
    'Vertex': 'शीर्ष',
    'Edge': 'किनारा',
    'Graph': 'ग्राफ',
    'Tree': 'पेड़',
    'Forest': 'जंगल',
    'Network': 'नेटवर्क',
    'Grid': 'ग्रिड',
    'Matrix': 'मैट्रिक्स',
    'Vector': 'वेक्टर',
    'Point': 'बिंदु',
    'Line': 'रेखा',
    'Curve': 'वक्र',
    'Surface': 'सतह',
    'Plane': 'समतल',
    'Space': 'अंतरिक्ष',
    'Dimension': 'आयाम',
    'Axis': 'अक्ष',
    'Coordinate': 'निर्देशांक',
    'Position': 'स्थिति',
    'Location': 'स्थान',
    'Place': 'जगह',
    'Spot': 'स्थान',
    'Point': 'बिंदु',
    'Area': 'क्षेत्र',
    'Region': 'क्षेत्र',
    'Zone': 'ज़ोन',
    'Territory': 'क्षेत्र',
    'Country': 'देश',
    'State': 'राज्य',
    'Province': 'प्रांत',
    'City': 'शहर',
    'Town': 'कस्बा',
    'Village': 'गांव',
    'Street': 'सड़क',
    'Road': 'सड़क',
    'Path': 'पथ',
    'Route': 'मार्ग',
    'Way': 'तरीका',
    'Direction': 'दिशा',
    'Course': 'पाठ्यक्रम',
    'Bearing': 'दिशा',
    'Heading': 'शीर्षक',
    'Orientation': 'अभिविन्यास',
    'Alignment': 'संरेखण'
}

def translate_text(text, translations):
    """Переводит текст используя словарь переводов"""
    if not text or not isinstance(text, str):
        return text
    
    # Исключаем строки с плейсхолдерами и техническими переменными
    exclude_patterns = [
        r'\{[^}]+\}',  # {variable}, {error}, {attempt} и т.д.
        r'FIREBASE_',  # FIREBASE_CONF, FIREBASE_USER и т.д.
        r'Config\.',   # Config.BOT_NAME и т.д.
        r'@[a-zA-Z_]+',  # @username, @bot_name и т.д.
        r'https?://',  # URL
        r'<[^>]+>',    # HTML теги
        r'`[^`]+`',    # Код в backticks
        r'[A-Z_]+_[A-Z_]+',  # Константы типа ERROR_MSG
    ]
    
    # Проверяем, содержит ли строка исключаемые паттерны
    for pattern in exclude_patterns:
        if re.search(pattern, text):
            return text  # Не переводим
    
    # Простой поиск и замена
    result = text
    for english, hindi in translations.items():
        # Заменяем только целые слова, но не внутри фигурных скобок
        pattern = r'\b' + re.escape(english) + r'\b'
        result = re.sub(pattern, hindi, result, flags=re.IGNORECASE)
    
    return result

def translate_messages_file(file_path, translations):
    """Переводит файл сообщений"""
    if not os.path.exists(file_path):
        print(f"Файл не найден: {file_path}")
        return
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Находим все строки с переменными (более точный паттерн)
    pattern = r'(\w+_MSG) = "([^"]*(?:\\.[^"]*)*)"'
    matches = re.findall(pattern, content)
    
    translated_count = 0
    for var_name, text in matches:
        # Пропускаем технические переменные
        if any(tech in var_name for tech in ['FIREBASE_', 'Config.', 'ADMIN_', 'DB_', 'MAGIC_']):
            continue
            
        # Пропускаем переменные с плейсхолдерами
        if re.search(r'\{[^}]+\}', text):
            continue
            
        translated_text = translate_text(text, translations)
        if translated_text != text:
            # Заменяем в содержимом
            old_line = f'{var_name} = "{text}"'
            new_line = f'{var_name} = "{translated_text}"'
            content = content.replace(old_line, new_line)
            translated_count += 1
            print(f"Переведено: {var_name}")
    
    # Сохраняем переведенный файл
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"Переведено {translated_count} переменных в {file_path}")

if __name__ == "__main__":
    # Переводим хинди файл
    in_file = "/mnt/c/Users/chelaxian/Desktop/tg-ytdlp-NEW/CONFIG/LANGUAGES/messages_IN.py"
    translate_messages_file(in_file, IN_TRANSLATIONS)
