from CONFIG.messages import Messages

class LoggerMsg(object):
    # Generic user/admin/access - removed unused variables

    # Removed unused variables
    
    # Missing variables that are used in code
    COOKIES_YOUTUBE_ALL_SOURCES_FAILED_ERROR_LOG_MSG = "Error logging: {e}"
    COOKIES_YOUTUBE_DOWNLOAD_EXCEPTION_LOG_MSG = "Exception during YouTube cookie download: {e}"
    COOKIES_YOUTUBE_FROM_SOURCE_FAILED_VALIDATION_LOG_MSG = "YouTube cookies from source {source_index} failed validation"
    
    # Removed - these are user messages, not logger messages
    
    # URL Extractor / start logs
    USER_STARTED_BOT = "{chat_id} - user started the bot"
    HELP_SENT_TO_USER = "Send help txt to user"
    ADD_BOT_TO_GROUP_SENT = "Send add_bot_to_group txt to user"

    # Image command logs
    IMG_HELP_SHOWN = "Showed /img help"
    INVALID_URL_PROVIDED = "Invalid URL provided: {url}"
    REPOSTED_CACHED_ALBUMS = "Reposted {count} cached albums for {url}"
    FAILED_ANALYZE_IMAGE = "Failed to analyze image URL: {url}"
    STREAMED_AND_SENT_MEDIA = "Streamed and sent {total_sent} media: {url}"
    IMAGE_COMMAND_ERROR = "Error in image command: {url}, error: {error}"

    # Search helper logs
    SEARCH_HELPER_OPENED = "User {user_id} opened search helper"
    SEARCH_HELPER_CLOSED = "User {user_id} closed search command"
    SEARCH_CALLBACK_ERROR = "Error in search callback handler: {error}"

    # Cache and sends
    PLAYLIST_VIDEOS_SENT_FROM_CACHE = "Playlist videos sent from cache (quality={quality}) to user {user_id}"
    VIDEO_SENT_FROM_CACHE = "Video sent from cache (quality={quality}) to user {user_id}"
    PLAYLIST_AUDIO_SENT_FROM_CACHE = "Playlist audio sent from cache (quality={quality}) to user {user_id}"
    AUDIO_SENT_FROM_CACHE = "Audio sent from cache (quality={quality}) to user {user_id}"

    # Limits and errors
    DOWNLOAD_TIMEOUT_LOG = "Download cancelled due to timeout"
    
    # Cookies command logs
    COOKIES_FAILED_START_BROWSER_LOG_MSG = "Failed to start cookies_from_browser: {e}"
    COOKIES_ERROR_FAST_COMMAND_LOG_MSG = "Error in fast command handling: {e}"
    COOKIES_YOUTUBE_TEST_FAILED_NO_INFO_LOG_MSG = "YouTube cookies test failed on user URL - no info returned for {cookie_file_path}"
    COOKIES_YOUTUBE_TEST_FAILED_MISSING_INFO_LOG_MSG = "YouTube cookies test failed on user URL - missing basic info for {cookie_file_path}"
    COOKIES_YOUTUBE_TEST_FAILED_INSUFFICIENT_FORMATS_LOG_MSG = "YouTube cookies test failed on user URL - insufficient formats ({formats_count}) for {cookie_file_path}"
    COOKIES_YOUTUBE_COOKIES_WORK_LOG_MSG = "YouTube cookies work on user URL for {cookie_file_path}"
    COOKIES_YOUTUBE_TEST_FAILED_USER_URL_LOG_MSG = "YouTube cookies test failed on user URL for {cookie_file_path}: {e}"
    COOKIES_YOUTUBE_TEST_FAILED_NO_INFO_RETURNED_LOG_MSG = "YouTube cookies test failed - no info returned for {cookie_file_path}"
    COOKIES_YOUTUBE_TEST_FAILED_MISSING_FIELDS_LOG_MSG = "YouTube cookies test failed - missing fields: {missing_fields} for {cookie_file_path}"
    COOKIES_YOUTUBE_TEST_FAILED_AVAILABLE_FIELDS_LOG_MSG = "Available fields: {available_fields}"
    COOKIES_YOUTUBE_TEST_FAILED_NO_FORMATS_LOG_MSG = "YouTube cookies test failed - no formats available for {cookie_file_path}"
    COOKIES_YOUTUBE_TEST_FAILED_INFO_KEYS_LOG_MSG = "Info keys: {info_keys}"
    COOKIES_YOUTUBE_TEST_FAILED_TITLE_TOO_SHORT_LOG_MSG = "YouTube cookies test failed - title too short: '{title}' for {cookie_file_path}"
    COOKIES_YOUTUBE_TEST_FAILED_TITLE_LENGTH_LOG_MSG = "Title length: {title_length}"
    COOKIES_YOUTUBE_TEST_FAILED_INVALID_DURATION_LOG_MSG = "YouTube cookies test failed - invalid duration: {duration} for {cookie_file_path}"
    COOKIES_YOUTUBE_TEST_FAILED_DURATION_SECONDS_LOG_MSG = "Duration in seconds: {duration}"
    COOKIES_YOUTUBE_TEST_FAILED_TOO_FEW_FORMATS_LOG_MSG = "YouTube cookies test failed - too few formats: {formats_count} for {cookie_file_path}"
    COOKIES_YOUTUBE_TEST_FAILED_AVAILABLE_FORMATS_LOG_MSG = "Available formats: {available_formats}"
    COOKIES_YOUTUBE_TEST_FAILED_ALL_FORMAT_IDS_LOG_MSG = "All format IDs: {all_format_ids}"
    COOKIES_YOUTUBE_TEST_PASSED_LOG_MSG = "YouTube cookies test passed for {cookie_file_path} - {formats_count} formats available"
    COOKIES_YOUTUBE_TEST_TITLE_LOG_MSG = "Title: '{title}'"
    COOKIES_YOUTUBE_TEST_DURATION_LOG_MSG = "Duration: {duration}s"
    COOKIES_YOUTUBE_TEST_UPLOADER_LOG_MSG = "Uploader: {uploader}"
    COOKIES_YOUTUBE_TEST_VIEW_COUNT_LOG_MSG = "View count: {view_count}"
    COOKIES_YOUTUBE_TEST_UPLOAD_DATE_LOG_MSG = "Upload date: {upload_date}"
    COOKIES_YOUTUBE_TEST_LIKE_COUNT_LOG_MSG = "Like count: {like_count}"
    COOKIES_YOUTUBE_TEST_FORMAT_IDS_LOG_MSG = "Format IDs: {format_ids}"
    COOKIES_YOUTUBE_TEST_UNAVAILABLE_LOG_MSG = "YouTube test video is unavailable (not a cookie issue): {e}"
    COOKIES_YOUTUBE_TEST_AUTH_ERROR_LOG_MSG = "YouTube cookies test failed - authentication/format error: {e}"
    COOKIES_YOUTUBE_TEST_OTHER_ERROR_LOG_MSG = "YouTube cookies test - other error (may not be cookie-related): {e}"
    COOKIES_YOUTUBE_TEST_EXCEPTION_LOG_MSG = "YouTube cookies test failed with exception: {e}"
    COOKIES_YOUTUBE_TEST_EXCEPTION_TYPE_LOG_MSG = "Exception type: {exception_type}"
    COOKIES_CANNOT_DETERMINE_USER_ID_LOG_MSG = "Cannot determine user_id from message object"
    COOKIES_ERROR_SENDING_MESSAGE_LOG_MSG = "Error sending message to user: {e}"
    COOKIES_FINAL_FALLBACK_SEND_FAILED_LOG_MSG = "Final fallback send failed: {e2}"
    COOKIES_YOUTUBE_URLS_EMPTY_LOG_MSG = "YouTube cookie URLs are empty for user {user_id}"
    COOKIES_ERROR_LOGGING_LOG_MSG = "Error logging: {e}"
    COOKIES_ERROR_SENDING_INITIAL_MESSAGE_LOG_MSG = "Error sending initial message: {e}"
    COOKIES_ERROR_UPDATING_MESSAGE_LOG_MSG = "Error updating message: {e}"
    COOKIES_YOUTUBE_COOKIE_ORDER_MODE_LOG_MSG = "YouTube cookie order mode: {order}"
    COOKIES_YOUTUBE_COOKIE_INDICES_ORDER_LOG_MSG = "YouTube cookie indices order: {indices}"
    COOKIES_YOUTUBE_DOWNLOAD_FAILED_LOG_MSG = "Failed to download YouTube cookie from URL {url_index}: status={status}, error={error}"
    COOKIES_YOUTUBE_URL_NOT_TXT_LOG_MSG = "YouTube cookie URL {url_index} is not .txt file"
    COOKIES_YOUTUBE_FILE_TOO_LARGE_LOG_MSG = "YouTube cookie file {url_index} is too large: {file_size} bytes"
    COOKIES_YOUTUBE_DOWNLOADED_VALIDATED_LOG_MSG = "YouTube cookies downloaded and validated for user {user_id} from source {source_index}"
    # Removed unused COOKIES_YOUTUBE_* variables
    COOKIES_YOUTUBE_CACHE_VALID_LOG_MSG = "Using cached YouTube cookie validation result for user {user_id} (cache valid for {cache_duration}s)"
    COOKIES_YOUTUBE_STARTING_ENSURE_LOG_MSG = "Starting ensure_working_youtube_cookies for user {user_id}"
    COOKIES_YOUTUBE_CHECKING_EXISTING_LOG_MSG = "Checking existing YouTube cookies for user {user_id}"
    COOKIES_YOUTUBE_EXISTING_WORKING_LOG_MSG = "Existing YouTube cookies are working for user {user_id}"
    COOKIES_YOUTUBE_FINISHED_EXISTING_WORKING_LOG_MSG = "Finished ensure_working_youtube_cookies for user {user_id} - existing cookies are working"
    COOKIES_YOUTUBE_EXISTING_FAILED_LOG_MSG = "Existing YouTube cookies failed test for user {user_id}, will try to update"
    COOKIES_YOUTUBE_NO_SOURCES_CONFIGURED_LOG_MSG = "No YouTube cookie sources configured for user {user_id}"
    COOKIES_YOUTUBE_ATTEMPTING_DOWNLOAD_LOG_MSG = "Attempting to download working YouTube cookies for user {user_id} from {sources_count} sources"
    COOKIES_YOUTUBE_TRYING_SOURCE_LOG_MSG = "Trying YouTube cookie source {source_index}/{total_sources} for user {user_id}"
    COOKIES_YOUTUBE_SOURCE_WORKING_LOG_MSG = "YouTube cookies from source {source_index} are working for user {user_id}"
    COOKIES_YOUTUBE_FINISHED_WORKING_FOUND_LOG_MSG = "Finished ensure_working_youtube_cookies for user {user_id} - working cookies found from source {source_index}"
    COOKIES_YOUTUBE_SOURCE_FAILED_VALIDATION_LOG_MSG = "YouTube cookies from source {source_index} failed validation for user {user_id}"
    COOKIES_YOUTUBE_PROCESSING_ERROR_LOG_MSG = "Error processing YouTube cookie URL {source_index} for user {user_id}: {e}"
    COOKIES_YOUTUBE_ALL_SOURCES_FAILED_REMOVING_LOG_MSG = "All YouTube cookie sources failed for user {user_id}, removing cookie file"
    COOKIES_YOUTUBE_FINISHED_NO_WORKING_LOG_MSG = "Finished ensure_working_youtube_cookies for user {user_id} - no working cookies found"
    COOKIES_YOUTUBE_RETRY_PROXY_LOG_MSG = "Attempting to retry download with proxy for user {user_id}"
    COOKIES_YOUTUBE_NO_PROXY_CONFIG_LOG_MSG = "No proxy configuration available for retry for user {user_id}"
    COOKIES_YOUTUBE_RETRY_PROXY_URL_LOG_MSG = "Retrying download with proxy: {proxy_url}"
    COOKIES_YOUTUBE_RETRY_PROXY_SUCCESS_LOG_MSG = "Download retry with proxy successful for user {user_id}"
    COOKIES_YOUTUBE_RETRY_PROXY_FAILED_LOG_MSG = "Download retry with proxy failed for user {user_id}"
    COOKIES_YOUTUBE_RETRY_PROXY_FAILED_ERROR_LOG_MSG = "Download retry with proxy failed for user {user_id}: {e}"
    COOKIES_YOUTUBE_RETRY_PROXY_SETUP_ERROR_LOG_MSG = "Error setting up proxy retry for user {user_id}: {e}"
    COOKIES_YOUTUBE_RETRY_ALREADY_IN_PROGRESS_LOG_MSG = "Retry already in progress for user {user_id}, skipping to avoid infinite loop"
    COOKIES_YOUTUBE_RETRY_DIFFERENT_COOKIES_LOG_MSG = "Attempting to retry download with different cookies for user {user_id}"
    COOKIES_YOUTUBE_RETRY_NO_SOURCES_LOG_MSG = "No YouTube cookie sources available for retry for user {user_id}"
    COOKIES_YOUTUBE_RETRY_SOURCES_ORDER_LOG_MSG = "Retrying download with cookie sources in order: {indices}"
    COOKIES_YOUTUBE_RETRY_ATTEMPT_LOG_MSG = "Retry attempt {attempt}/{total_attempts} with cookie source {source_index} for user {user_id}"
    COOKIES_YOUTUBE_RETRY_DOWNLOAD_FAILED_LOG_MSG = "Failed to download cookie from source {source_index}: status={status}, error={error}"
    COOKIES_YOUTUBE_RETRY_URL_NOT_TXT_LOG_MSG = "Cookie URL {source_index} is not .txt file"
    COOKIES_YOUTUBE_RETRY_FILE_TOO_LARGE_LOG_MSG = "Cookie file {source_index} is too large: {file_size} bytes"
    COOKIES_YOUTUBE_RETRY_SOURCE_WORKING_LOG_MSG = "Cookie source {source_index} is working, retrying download for user {user_id}"
    COOKIES_YOUTUBE_RETRY_SUCCESS_LOG_MSG = "Download retry successful with cookie source {source_index} for user {user_id}"
    COOKIES_YOUTUBE_RETRY_FAILED_LOG_MSG = "Download retry failed with cookie source {source_index} for user {user_id}"
    COOKIES_YOUTUBE_RETRY_FAILED_ERROR_LOG_MSG = "Download retry failed with cookie source {source_index} for user {user_id}: {e}"
    COOKIES_YOUTUBE_RETRY_ERROR_COOKIE_RELATED_LOG_MSG = "Error is cookie-related, trying next source for user {user_id}"
    COOKIES_YOUTUBE_RETRY_ERROR_NOT_COOKIE_RELATED_LOG_MSG = "Error is not cookie-related, stopping retry for user {user_id}"
    COOKIES_YOUTUBE_RETRY_SOURCE_FAILED_VALIDATION_LOG_MSG = "Cookie source {source_index} failed validation for user {user_id}"
    COOKIES_YOUTUBE_RETRY_PROCESSING_ERROR_LOG_MSG = "Error processing cookie source {source_index} for user {user_id}: {e}"
    COOKIES_YOUTUBE_RETRY_ALL_SOURCES_FAILED_LOG_MSG = "All cookie sources failed for retry download for user {user_id}"
    COOKIES_YOUTUBE_CACHE_CLEARED_LOG_MSG = "Cleared YouTube cookie validation cache for user {user_id}"
    COOKIES_YOUTUBE_CACHE_NO_ENTRY_LOG_MSG = "No cache entry found for user {user_id}"
    COOKIES_YOUTUBE_TEST_FAILED_MISSING_FIELDS_LOG_MSG = "YouTube cookies test failed - missing fields: {missing_fields} for {cookie_file_path}"
    COOKIES_YOUTUBE_TEST_FAILED_NO_FORMATS_LOG_MSG = "YouTube cookies test failed - no formats available for {cookie_file_path}"
    COOKIES_YOUTUBE_TEST_FAILED_INVALID_DURATION_LOG_MSG = "YouTube cookies test failed - invalid duration: {duration} for {cookie_file_path}"
    COOKIES_YOUTUBE_TEST_FAILED_TOO_FEW_FORMATS_LOG_MSG = "YouTube cookies test failed - too few formats: {formats_count} for {cookie_file_path}"
    COOKIES_YOUTUBE_TEST_PASSED_LOG_MSG = "YouTube cookies test passed for {cookie_file_path} - {formats_count} formats available"
    COOKIES_YOUTUBE_TEST_TITLE_LOG_MSG = "Title: '{title}'"
    COOKIES_YOUTUBE_TEST_DURATION_LOG_MSG = "Duration: {duration}s"
    COOKIES_YOUTUBE_TEST_UPLOADER_LOG_MSG = "Uploader: {uploader}"
    COOKIES_YOUTUBE_TEST_VIEW_COUNT_LOG_MSG = "View count: {view_count}"
    COOKIES_YOUTUBE_TEST_UPLOAD_DATE_LOG_MSG = "Upload date: {upload_date}"
    COOKIES_YOUTUBE_TEST_LIKE_COUNT_LOG_MSG = "Like count: {like_count}"
    COOKIES_YOUTUBE_TEST_FORMAT_IDS_LOG_MSG = "Format IDs: {format_ids}"
    COOKIES_YOUTUBE_TEST_AUTH_ERROR_LOG_MSG = "YouTube cookies test failed - authentication/format error: {e}"
    COOKIES_YOUTUBE_TEST_OTHER_ERROR_LOG_MSG = "YouTube cookies test - other error (may not be cookie-related): {e}"
    COOKIES_YOUTUBE_TEST_EXCEPTION_TYPE_LOG_MSG = "Exception type: {exception_type}"
    COOKIES_ERROR_SENDING_MESSAGE_LOG_MSG = "Error sending message to user: {e}"
    COOKIES_FINAL_FALLBACK_SEND_FAILED_LOG_MSG = "Final fallback send failed: {e}"
    COOKIES_YOUTUBE_URLS_EMPTY_LOG_MSG = "YouTube cookie URLs are empty for user {user_id}"
    COOKIES_ERROR_UPDATING_MESSAGE_LOG_MSG = "Error updating message: {e}"
    COOKIES_YOUTUBE_URL_NOT_TXT_LOG_MSG = "YouTube cookie URL {idx} is not .txt file"
    COOKIES_YOUTUBE_FILE_TOO_LARGE_LOG_MSG = "YouTube cookie file {idx} is too large: {size} bytes"
    COOKIES_YOUTUBE_DOWNLOADED_VALIDATED_LOG_MSG = "YouTube cookies downloaded and validated for user {user_id} from source {idx}"
    COOKIES_YOUTUBE_ALL_SOURCES_FAILED_LOG_MSG = "All YouTube cookie sources failed for user {user_id}"
    COOKIES_YOUTUBE_EXISTING_WORKING_LOG_MSG = "Existing YouTube cookies are working for user {user_id}"
    COOKIES_YOUTUBE_NO_SOURCES_CONFIGURED_LOG_MSG = "No YouTube cookie sources configured for user {user_id}"
    COOKIES_YOUTUBE_ATTEMPTING_DOWNLOAD_LOG_MSG = "Attempting to download working YouTube cookies for user {user_id} from {count} sources"
    COOKIES_YOUTUBE_TRYING_SOURCE_LOG_MSG = "Trying YouTube cookie source {i}/{total} for user {user_id}"
    COOKIES_YOUTUBE_SOURCE_WORKING_LOG_MSG = "YouTube cookies from source {i} are working for user {user_id}"
    COOKIES_YOUTUBE_SOURCE_FAILED_VALIDATION_LOG_MSG = "YouTube cookies from source {i} failed validation for user {user_id}"
    COOKIES_YOUTUBE_FINISHED_NO_WORKING_LOG_MSG = "Finished ensure_working_youtube_cookies for user {user_id} - no working cookies found"
    COOKIES_YOUTUBE_RETRY_PROXY_SUCCESS_LOG_MSG = "Download retry with proxy successful for user {user_id}"
    COOKIES_YOUTUBE_RETRY_PROXY_FAILED_LOG_MSG = "Download retry with proxy failed for user {user_id}"
    COOKIES_YOUTUBE_RETRY_ATTEMPT_LOG_MSG = "Retry attempt {attempt}/{total} with cookie source {idx} for user {user_id}"
    COOKIES_YOUTUBE_RETRY_URL_NOT_TXT_LOG_MSG = "Cookie URL {idx} is not .txt file"
    COOKIES_YOUTUBE_RETRY_FILE_TOO_LARGE_LOG_MSG = "Cookie file {idx} is too large: {size} bytes"
    COOKIES_YOUTUBE_RETRY_SOURCE_WORKING_LOG_MSG = "Cookie source {idx} is working, retrying download for user {user_id}"
    COOKIES_YOUTUBE_RETRY_SUCCESS_LOG_MSG = "Download retry successful with cookie source {idx} for user {user_id}"
    COOKIES_YOUTUBE_RETRY_FAILED_ERROR_LOG_MSG = "Download retry failed with cookie source {idx} for user {user_id}: {e}"
    COOKIES_YOUTUBE_RETRY_ERROR_COOKIE_RELATED_LOG_MSG = "Error is cookie-related, trying next source for user {user_id}"
    COOKIES_YOUTUBE_RETRY_ALL_SOURCES_FAILED_LOG_MSG = "All cookie sources failed for retry download for user {user_id}"
    COOKIES_YOUTUBE_CACHE_CLEARED_LOG_MSG = "Cleared all YouTube cookie validation cache"
    
    # Image command specific logs
    IMG_PAID_EMBEDDED_COVER_LOG_MSG = "[IMG PAID] Embedded cover into video: {video_path}"
    IMG_PAID_FAILED_EMBED_COVER_LOG_MSG = "[IMG PAID] Failed to embed cover into video {video_path}: {e}"
    IMG_LOG_OPEN_COPY_SENT_LOG_MSG = "[IMG LOG] Open copy sent to NSFW channel for history: {file_path}"
    IMG_LOG_FAILED_SEND_OPEN_COPY_LOG_MSG = "[IMG LOG] Failed to send open copy to NSFW channel: {e}"
    IMG_CACHE_SKIP_NSFW_LOG_MSG = "[IMG CACHE] Skipping cache save for NSFW content: index={album_index}, channel_type={channel_type}"
    IMG_CACHE_SAVE_ALBUM_LOG_MSG = "[IMG CACHE] About to save album: index={album_index}, ids={message_ids}, channel_type={channel_type}"
    IMG_CACHE_SAVE_REQUESTED_LOG_MSG = "[IMG CACHE] Save requested for index={album_index}, channel_type={channel_type}"
    IMG_CACHE_SAVE_FAILED_LOG_MSG = "[IMG CACHE] Save failed for index={album_index}: {e}"
    IMG_CONVERTED_WEBP_JPEG_LOG_MSG = "Converted WebP to JPEG: {file_path} -> {output_path}"
    IMG_FAILED_CONVERT_WEBP_LOG_MSG = "Failed to convert WebP: {result_stderr}"
    IMG_CONVERTED_WEBM_MP4_LOG_MSG = "Converted WebM to MP4: {file_path} -> {output_path}"
    IMG_FAILED_CONVERT_WEBM_LOG_MSG = "Failed to convert WebM: {result_stderr}"
    IMG_REMUXED_MP4_FASTSTART_LOG_MSG = "Remuxed MP4 with faststart: {file_path} -> {output_path}"
    IMG_FAILED_REMUX_MP4_LOG_MSG = "Failed to remux MP4 faststart: {result_stderr}"
    IMG_CONVERTED_TO_MP4_LOG_MSG = "Converted {file_ext} to MP4: {file_path} -> {output_path}"
    IMG_FAILED_CONVERT_TO_MP4_LOG_MSG = "Failed to convert {file_ext}: {result_stderr}"
    IMG_CONVERTED_TO_JPEG_LOG_MSG = "Converted {file_ext} to JPEG: {file_path} -> {output_path}"
    IMG_FAILED_CONVERT_TO_JPEG_LOG_MSG = "Failed to convert {file_ext}: {result_stderr}"
    IMG_CONVERSION_TIMEOUT_LOG_MSG = "Conversion timeout for {file_path}"
    IMG_CONVERSION_ERROR_LOG_MSG = "Conversion error for {file_path}: {e}"
    IMG_DEBUG_EXTRACT_URL_RANGE_LOG_MSG = "[IMG DEBUG] extract_url_range_tags result: parsed_url={parsed_url}, _s={_s}, _e={_e}, text={text}"
    IMG_DEBUG_RANGE_DETECTED_LOG_MSG = "[IMG DEBUG] Range detected: {_s}-{_e}"
    IMG_DEBUG_NO_RANGE_LOG_MSG = "[IMG DEBUG] No range detected in URL*start*end format"
    IMG_ERROR_GET_CACHED_POSTS_LOG_MSG = "Error getting cached image posts: {e}"
    IMG_CACHE_REPOSTING_ALBUM_LOG_MSG = "[IMG CACHE] Reposting album {album_idx} from channel {from_chat_id} to user {user_id}, message_ids={ids}"
    IMG_CACHE_FALLBACK_REPOSTING_LOG_MSG = "[IMG CACHE] Fallback reposting album {album_idx} from channel {from_chat_id} to user {user_id}, message_ids={ids}"
    IMG_CACHE_FAILED_FORWARD_ALBUM_LOG_MSG = "Failed to forward cached album {album_idx}: {_e}"
    IMG_CACHE_FORWARD_EARLY_FAILED_LOG_MSG = "Image cache forward (early) failed: {_e}"
    IMG_USER_ADMIN_LIMIT_LOG_MSG = "[IMG] User {user_id} is admin: {is_admin}, limit: {limit_text}"
    IMG_PRE_CLEANUP_START_LOG_MSG = "[IMG PRE-CLEANUP] Starting pre-cleanup of user directory: users/{user_id}"
    IMG_PRE_CLEANUP_REMOVED_FILE_LOG_MSG = "[IMG PRE-CLEANUP] Removed file: {file_path}"
    IMG_PRE_CLEANUP_FAILED_REMOVE_FILE_LOG_MSG = "[IMG PRE-CLEANUP] Failed to remove {file_path}: {e}"
    IMG_PRE_CLEANUP_REMOVED_DIR_LOG_MSG = "[IMG PRE-CLEANUP] Removed empty directory: {dir_path}"
    IMG_PRE_CLEANUP_FAILED_REMOVE_DIR_LOG_MSG = "[IMG PRE-CLEANUP] Failed to remove directory {dir_path}: {e}"
    IMG_PRE_CLEANUP_COMPLETED_LOG_MSG = "[IMG PRE-CLEANUP] Pre-cleanup completed"
    IMG_PRE_CLEANUP_FAILED_LOG_MSG = "[IMG PRE-CLEANUP] Failed to perform pre-cleanup: {e}"
    IMG_BATCH_SMALL_TOTAL_LOG_MSG = "[IMG BATCH] Small total detected: {detected_total}, setting end cap to {manual_end_cap}"
    IMG_DOWNLOADING_RANGE_1_1_LOG_MSG = "Downloading with range 1-1 (total={detected_total}, start={current_start}, end={next_end})"
    IMG_CLI_DOWNLOAD_FAILED_LOG_MSG = "CLI download failed, trying Python API."
    IMG_PREPARED_RANGE_LOG_MSG = "Prepared range: {range_expr}"
    IMG_CLI_RANGE_FAILED_LOG_MSG = "CLI range download failed or rejected for {range_expr}, trying Python API."
    IMG_BATCH_TOTAL_TIMEOUT_LOG_MSG = "[IMG BATCH] Total timeout reached ({max_total_wait_time}s), stopping download after {total_elapsed:.1f}s"
    IMG_BATCH_INACTIVITY_TIMEOUT_LOG_MSG = "[IMG BATCH] Inactivity timeout reached ({max_inactivity_time}s), no new files found for {inactivity_elapsed:.1f}s"
    IMG_BATCH_STARTING_DOWNLOAD_RANGE_LOG_MSG = "[IMG BATCH] Starting download range {current_start}-{next_end}"
    IMG_BATCH_NO_FILES_DOWNLOADED_LOG_MSG = "[IMG BATCH] No files downloaded in range {current_start}-{next_end}, proceeding to file search"
    IMG_BATCH_FOUND_FILES_LOG_MSG = "[IMG BATCH] Successfully found {files_downloaded_in_range} files"
    IMG_BATCH_MEDIA_ENDED_LOG_MSG = "[IMG BATCH] Media appears to have ended - got {files_downloaded_in_range} files instead of expected {expected_files}"
    IMG_BATCH_SEARCHING_FILES_LOG_MSG = "[IMG BATCH] Searching for files in: {search_dir}"
    IMG_BATCH_FOUND_FILES_IN_DIR_LOG_MSG = "[IMG BATCH] Found {file_count} files in: {root}"
    IMG_BATCH_FOUND_SUBDIRS_LOG_MSG = "[IMG BATCH] Found subdirectories: {dirs}"
    IMG_BATCH_SKIPPING_ZERO_FILE_LOG_MSG = "[IMG BATCH] Skipping zero-size file: {file_path}"
    IMG_BATCH_OTHERS_DELETED_FILE_LOG_MSG = "[IMG BATCH OTHERS] Deleted file: {p}"
    IMG_BATCH_OTHERS_FAILED_DELETE_LOG_MSG = "[IMG BATCH OTHERS] Failed to delete {p}: {e}"
    IMG_BATCH_OTHERS_FAILED_ZERO_LOG_MSG = "[IMG BATCH OTHERS] Failed to zero out original {orig}: {e}"
    IMG_CLEANUP_START_LOG_MSG = "[IMG CLEANUP] Starting final cleanup of user directory: {run_dir}"
    IMG_CLEANUP_REMOVED_FILE_LOG_MSG = "[IMG CLEANUP] Removed file: {file_path}"
    IMG_CLEANUP_FAILED_REMOVE_LOG_MSG = "[IMG CLEANUP] Failed to remove {file_path}: {e}"
    IMG_CLEANUP_REMOVED_DIR_LOG_MSG = "[IMG CLEANUP] Removed empty directory: {dir_path}"
    
    # More IMG logs
    IMG_FATAL_ERROR_DETECTED_LOG_MSG = "Fatal error detected: {result}"
    IMG_BATCH_DOWNLOADED_FILES_LOG_MSG = "[IMG BATCH] Downloaded {files_downloaded_in_range} files in range {current_start}-{next_end} (expected {expected_files}) in {elapsed_time:.1f}s"
    IMG_MAIN_FAKE_MESSAGE_LOG_MSG = "[IMG MAIN] FAKE MESSAGE DETECTED - original_chat_id={original_chat_id}, is_private_chat={is_private_chat}"
    IMG_MAIN_NSFW_FLAG_LOG_MSG = "[IMG MAIN] nsfw_flag={nsfw_flag}, is_private_chat={is_private_chat}, media_group_len={media_group_len}"
    IMG_MAIN_PAID_LOGIC_LOG_MSG = "[IMG MAIN] Entering paid media logic for {item_count} items"
    IMG_PAID_SENDING_ALBUM_LOG_MSG = "[IMG PAID] Sending paid media album with {item_count} items"
    IMG_PAID_MEDIA_TYPES_LOG_MSG = "[IMG PAID] Media types: {media_types}"
    IMG_PAID_ATTEMPTING_ALBUM_LOG_MSG = "[IMG PAID] Attempting to send album with {item_count} items to user {user_id}"
    IMG_PAID_ALBUM_DETAILS_LOG_MSG = "[IMG PAID] Album details: star_count={star_count}, payload={payload}"
    
    # More IMG PAID and FALLBACK logs
    IMG_FAILED_SEND_PAID_MEDIA_ALBUM_LOG_MSG = "Failed to send paid media album: {e}"
    IMG_ALBUM_CAPTION_NORMALIZATION_SKIPPED_LOG_MSG = "[IMG] Album caption normalization skipped: {_e}"
    IMG_FLOODWAIT_SEND_MEDIA_GROUP_LOG_MSG = "FloodWait while send_media_group: waiting {wait_s}s and retrying (attempt {attempts}+1}/5)"
    IMG_CACHE_COPYING_ALBUM_LOG_MSG = "[IMG CACHE] Copying album to logs, orig_ids={orig_ids}"
    IMG_LOG_FAKE_MESSAGE_DETECTED_LOG_MSG = "[IMG LOG] FAKE MESSAGE DETECTED - original_chat_id={original_chat_id}, is_private_chat={is_private_chat}"
    
    # Video extractor logs
    VIDEO_EXTRACTOR_SAVED_FORMAT_LOG_MSG = "video_url_extractor: using saved format '{saved_format}', quality_key='{quality_key}'"
    
    # URL extractor logs
    URL_EXTRACTOR_VIDEO_EXTRACTOR_FAILED_LOG_MSG = "video_url_extractor failed, fallback to gallery-dl: {e}"
    URL_EXTRACTOR_GALLERY_DL_FALLBACK_FAILED_LOG_MSG = "gallery-dl fallback also failed: {e2}"
    URL_EXTRACTOR_NO_MATCHING_COMMAND_LOG_MSG = "{user_id} No matching command processed."
    URL_EXTRACTOR_ADD_GROUP_HELPER_CLOSED_LOG_MSG = "🤖 Add bot to group helper closed"
    URL_EXTRACTOR_ADD_GROUP_CALLBACK_ERROR_LOG_MSG = "Error in add_group_msg callback handler: {e}"
    URL_EXTRACTOR_REMOVED_FILE_LOG_MSG = "Removed file: {file_path}"
    URL_EXTRACTOR_FAILED_REMOVE_FILE_LOG_MSG = "Failed to remove file {file_path}: {e}"
    URL_EXTRACTOR_FAILED_CLEAR_YOUTUBE_CACHE_LOG_MSG = "Failed to clear YouTube cookie cache: {e}"
    
    # Thumbnail downloader logs
    THUMBNAIL_DOWNLOADER_VK_FAILED_LOG_MSG = "Failed to download VK thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_TIKTOK_FAILED_LOG_MSG = "Failed to download TikTok thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_TWITTER_FAILED_LOG_MSG = "Failed to download Twitter thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_FACEBOOK_FAILED_LOG_MSG = "Failed to download Facebook thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_PORNHUB_FAILED_LOG_MSG = "Failed to download Pornhub thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_INSTAGRAM_ATTEMPT_LOG_MSG = "Attempting to download Instagram thumbnail for video_id: {video_id}"
    THUMBNAIL_DOWNLOADER_INSTAGRAM_NOT_IMPLEMENTED_LOG_MSG = "Instagram thumbnail download not implemented"
    THUMBNAIL_DOWNLOADER_INSTAGRAM_FAILED_LOG_MSG = "Failed to download Instagram thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_VIMEO_FAILED_LOG_MSG = "Failed to download Vimeo thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_DAILYMOTION_FAILED_LOG_MSG = "Failed to download Dailymotion thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_RUTUBE_FAILED_LOG_MSG = "Failed to download Rutube thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_TWITCH_FAILED_LOG_MSG = "Failed to download Twitch thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_BOOSTY_FAILED_LOG_MSG = "Failed to download Boosty thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_ODNOKLASSNIKI_FAILED_LOG_MSG = "Failed to download Odnoklassniki thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_REDDIT_FAILED_LOG_MSG = "Failed to download Reddit thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_PIKABU_FAILED_LOG_MSG = "Failed to download Pikabu thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_YANDEX_DZEN_FAILED_LOG_MSG = "Failed to download Yandex.Dzen thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_GOOGLE_DRIVE_FAILED_LOG_MSG = "Failed to download Google Drive thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_REDTUBE_FAILED_LOG_MSG = "Failed to download Redtube thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_BILIBILI_FAILED_LOG_MSG = "Failed to download Bilibili thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_NICONICO_FAILED_LOG_MSG = "Failed to download Niconico thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_XVIDEOS_FAILED_LOG_MSG = "Failed to download XVideos thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_YOUPORN_FAILED_LOG_MSG = "Failed to download YouPorn thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_XHAMSTER_FAILED_LOG_MSG = "Failed to download XHamster thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_PORNTUBE_FAILED_LOG_MSG = "Failed to download PornTube thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_SPANKBANG_FAILED_LOG_MSG = "Failed to download SpankBang thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_YOUTUBE_FAILED_LOG_MSG = "Failed to download YouTube thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_XNXX_FAILED_LOG_MSG = "Failed to download XNXX thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_ONLYFANS_FAILED_LOG_MSG = "Failed to download OnlyFans thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_PATREON_FAILED_LOG_MSG = "Failed to download Patreon thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_SOUNDCLOUD_FAILED_LOG_MSG = "Failed to download SoundCloud thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_BANDCAMP_FAILED_LOG_MSG = "Failed to download Bandcamp thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_MIXCLOUD_FAILED_LOG_MSG = "Failed to download Mixcloud thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_DEEZER_FAILED_LOG_MSG = "Failed to download Deezer thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_SPOTIFY_FAILED_LOG_MSG = "Failed to download Spotify thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_APPLE_MUSIC_FAILED_LOG_MSG = "Failed to download Apple Music thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_TIDAL_FAILED_LOG_MSG = "Failed to download Tidal thumbnail: {e}"
    THUMBNAIL_DOWNLOADER_UNIVERSAL_CALLED_LOG_MSG = "Universal thumbnail downloader called for URL: {url}"
    THUMBNAIL_DOWNLOADER_SERVICE_DETECTED_LOG_MSG = "Detected service: {service}, video_id: {video_id}"
    THUMBNAIL_DOWNLOADER_NO_VIDEO_ID_LOG_MSG = "Could not extract video ID from URL: {url}"
    THUMBNAIL_DOWNLOADER_SUCCESS_LOG_MSG = "Successfully downloaded {service} thumbnail to {dest}"
    THUMBNAIL_DOWNLOADER_SERVICE_FAILED_LOG_MSG = "Service-specific thumbnail download failed for {service}, will use fallback"
    THUMBNAIL_DOWNLOADER_ERROR_LOG_MSG = "Error in universal thumbnail downloader: {e}"
    THUMBNAIL_DOWNLOADER_TELEGRAM_EMBED_FAILED_LOG_MSG = "Failed to get Telegram embed thumbnail: {e}"

